<?php
/**
 * @file
 * Code for the BB HR Applicant feature.
 */

include_once 'bb_hr_applicant.features.inc';

/**
 * Implements hook_theme
 */
function bb_hr_applicant_theme() {
  return array(
    // Register the template specific for the resume profile teaser.
    'profile2__cv__teaser' => array(
    'render element' => 'elements',
    'template' => 'profile--cv--teaser',
    ),
  );
}

/**
 * Implements hook_profile2_view
 */
function bb_hr_applicant_profile2_view($profile, $view_mode, $langcode) {

  $profile_wrapper = entity_metadata_wrapper('profile2', $profile);
  $user_name = $profile_wrapper->user->value()->name;

  $profile->label = $user_name;
}