<?php
/**
 * @file
 * Code for the BB HR Recruiter feature.
 */

include_once 'bb_hr_recruiter.features.inc';

/**
 * Implements hook_menu
 */
function bb_hr_recruiter_menu() {
  $items = array();

	$items['admin/recruiter'] = array(
		'title' => 'Recruiter',
		'description' => 'Recruiter functionalities.',
		'position' => 'right',
		'weight' => -11,
		'page callback' => 'system_admin_menu_block_page',
		'access arguments' => array('access administration pages'),
		'file' =>  '/system.admin.inc',
		'file path' => drupal_get_path('module', 'system'),
	);
	
	return $items;
}