<?php
/**
 * @file
 * bb_hr_job_search.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function bb_hr_job_search_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-123ZakQutnazp9Q5VV4dGfR2iZyGNkFi'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '123ZakQutnazp9Q5VV4dGfR2iZyGNkFi',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'brightbrain' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'brightbrain',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Ervaring',
    'visibility' => 0,
  );

  $export['facetapi-1UuE3MfhjlTg7j1uMAK8livdLCA02Z0G'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '1UuE3MfhjlTg7j1uMAK8livdLCA02Z0G',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'brightbrain' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'brightbrain',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Skills Algemeen',
    'visibility' => 0,
  );

  $export['facetapi-5WeLUXLQYB6myGK1nXd721FxmefhJJtp'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '5WeLUXLQYB6myGK1nXd721FxmefhJJtp',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'brightbrain' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'brightbrain',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Studiedomein',
    'visibility' => 0,
  );

  $export['facetapi-f3NI1sU3W53tqHIWtKI29iYIETsskvpC'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'f3NI1sU3W53tqHIWtKI29iYIETsskvpC',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'brightbrain' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'brightbrain',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Skills IT',
    'visibility' => 0,
  );

  $export['facetapi-h2b71amScG8Sx0mG50Kyb4IAkeToqrm3'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'h2b71amScG8Sx0mG50Kyb4IAkeToqrm3',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'brightbrain' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'brightbrain',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Talen',
    'visibility' => 0,
  );

  $export['facetapi-q29aExfsFLNQiqAOeYEx8tE6W5YyGTe9'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'q29aExfsFLNQiqAOeYEx8tE6W5YyGTe9',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'brightbrain' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'brightbrain',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Diploma',
    'visibility' => 0,
  );

  $export['facetapi-qO2aQ1pOhH01tykI7iO0fVyYYhsLtVTK'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'qO2aQ1pOhH01tykI7iO0fVyYYhsLtVTK',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'brightbrain' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'brightbrain',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Werkdomein',
    'visibility' => 0,
  );

  $export['facetapi-v8OT33llPN3ejhlfbqjoLxQDpoQrpr2g'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'v8OT33llPN3ejhlfbqjoLxQDpoQrpr2g',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'brightbrain' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'brightbrain',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'zen' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'zen',
        'weight' => 0,
      ),
    ),
    'title' => 'Type contract',
    'visibility' => 0,
  );

  return $export;
}
